# Generated by Django 4.2.1 on 2023-05-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
