# Generated by Django 4.2.1 on 2023-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_part_category_delete_category_delete_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkMode',
        ),
    ]
