# Generated by Django 4.2.1 on 2023-05-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkmode',
            name='user',
        ),
    ]
