# Generated by Django 4.2.1 on 2023-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_darkmode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkmode',
            name='shadow',
            field=models.CharField(default='drop-shadow-sm', max_length=20),
        ),
    ]
