# Generated by Django 4.2.1 on 2023-05-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_darkmode_shadow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkMode',
        ),
    ]
