# Generated by Django 4.2.1 on 2023-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_darkmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_shadow', models.CharField(default='drop-shadow-sm', max_length=20)),
            ],
        ),
    ]
