# Generated by Django 4.2.1 on 2023-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkMode',
        ),
    ]
