# Generated by Django 4.2.1 on 2023-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_delete_darkmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('mode', models.CharField(default='Light', max_length=10)),
                ('body', models.CharField(default='bg-gray-300', max_length=20)),
                ('nav', models.CharField(default='bg-gray-200', max_length=20)),
                ('nav_shadow', models.CharField(default='drop-shadow-sm', max_length=20)),
            ],
        ),
    ]
