# Generated by Django 4.2.1 on 2023-05-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_darkmode_nav_shadow_alter_darkmode_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkmode',
            name='main',
            field=models.CharField(default='bg-slate-500', max_length=64),
        ),
        migrations.AlterField(
            model_name='darkmode',
            name='body',
            field=models.CharField(default='bg-white text-white', max_length=64),
        ),
        migrations.AlterField(
            model_name='darkmode',
            name='nav',
            field=models.CharField(default='text-gray-400', max_length=64),
        ),
    ]
