# Generated by Django 4.2.1 on 2023-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_main_darkmode_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkmode',
            name='bg',
        ),
        migrations.AddField(
            model_name='darkmode',
            name='hover',
            field=models.CharField(default='hover:bg-slate-100 hover:text-slate-900', max_length=64),
        ),
    ]
