# Generated by Django 4.2.1 on 2023-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
