# Generated by Django 4.2.1 on 2023-05-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.category'),
        ),
    ]
