# Generated by Django 4.2.1 on 2023-05-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_delete_inventory_delete_log_remove_part_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('user', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('user', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
