# Generated by Django 4.2.1 on 2023-05-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
